services:
  - type: web
    name: email-classifier
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"