services:
  - type: web
    name: email-classifier
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn_config.py run:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.10"
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"