services:
  # Web Service
  - type: web
    name: email-classifier
    runtime: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn --config gunicorn_config.py run:app"
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "false"
    autoDeploy: true
    
  # PostgreSQL Database (opcional - pode usar PostgreSQL externo)
  # - type: pserv
  #   name: email-classifier-db
  #   runtime: postgresql
  #   plan: free
  #   disk:
  #     name: email-classifier-db
  #     mountPath: /var/lib/postgresql/data
  #     sizeGB: 1