"""Adicionar campo timestamp ao EmailClassification

Revision ID: bb83f3e9e6d3
Revises: 09fe2a329996
Create Date: 2025-09-28 08:02:10.717557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb83f3e9e6d3'
down_revision = '09fe2a329996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_classifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_classifications', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
