"""Increase password_hash field length to 255 characters

Revision ID: password_hash_255
Revises: bb83f3e9e6d3
Create Date: 2025-09-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'password_hash_255'
down_revision = 'bb83f3e9e6d3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=255),
                    existing_nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=False)
    # ### end Alembic commands ###